Add setup pass to run */dh/setup scripts
We run the dh/setup scripts (executables of any kind with that name,
actually) after all the other passes to ensure that they're working
with a completely updated tree. Otherwise they might not see things
that they'd use that have not yet come in.

The CWD for these scripts is defined to be in the module itself, and
we do a couple of simple checks for this in the tests.

The testing of this isn't really complete; it's entirely in the "All
together now" pass and doesn't test that we get a proper warning about
error code returns from trying to run the script (though we do
actually print it and it's been tested "by hand").

diff --git a/bin/dot-home-setup b/bin/dot-home-setup
--- a/bin/dot-home-setup
+++ b/bin/dot-home-setup
@@ -308,6 +308,18 @@ run_clean_legacy_bin_pass() {
 }
 
 ############################################################
+# run setup scripts pass
+
+run_setup_pass() {
+    echo "===== Running dh/setup scripts"
+    for module in *; do
+        [[ -e $module/dh/setup ]] || continue
+        echo "----- $module"
+        (cd "$module" && dh/setup) || warn "Failure exit with $?"
+    done
+}
+
+############################################################
 # Main
 
 do_update=false
@@ -319,7 +331,7 @@ while [ -n "$1" ]; do case "$1" in
     *)                          die "Unknown argument: $1";;
 esac; done
 [ -z "$passes" ] && passes=(
-    dependencies inb4check inb4build symlink clean_legacy_bin)
+    dependencies inb4check inb4build symlink clean_legacy_bin setup)
 $do_update       && passes=("update" "${passes[@]}");
 
 cd "$HOME"/.home/ 2>/dev/null || die "Cannot change to $HOME/.home/."
